### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by eirini81** [ronnetzer/monday-vs-code-wiki#1]
I get this Error in the browser when trying to sign in through the editor: 
{"error":"invalid_scope","error_description":"Invalid scope param"}

**Comment by fundamental-callum** [comment]
Same here

**Comment by crosenblumrelief** [comment]
Same here. Any update?

**Comment by ronnetzer** [comment]
Hi all, thank you for reporting the issue.
This project was created as part of challenge, it was never intended for production use and isn't maintained at all.
You're more than welcome to fork it and take it from there.
